const { Photo } = require('../models');

// Types of photos 
const photodata = [
  {
    title: 'Cali',
    artist: 'FUGG',
    category: 'June 2021',
    gallery_id: 1,
    filename: 'cali2.jpg',
    description:'Cali boys',
  },
  {
    title: 'Cali',
    artist: 'FUGG',
    category: 'June 2021',
    gallery_id: 1,
    filename: 'cali3.jpg',
    description:'Cali boys',
  },
  {
    title: 'Cali',
    artist: 'FUGG',
    category: 'June 2021',
    gallery_id: 1,
    filename: 'cali4.jpg',
    description:'Cali boys',
  },
  {
    title: 'Cali',
    artist: 'FUGG',
    category: 'June 2021',
    gallery_id: 1,
    filename: 'cali5.jpg',
    description:'Cali boys',
  },
  {
    title: 'Cali',
    artist: 'FUGG',
    category: 'June 2021',
    gallery_id: 1,
    filename: 'cali6.jpg',
    description:'Cali boys',
  },
  {
    title: 'Cali',
    artist: 'FUGG',
    category: 'June 2021',
    gallery_id: 1,
    filename: 'cali7.jpg',
    description:'Cali boys',
  },
  {
    title: 'Cali',
    artist: 'FUGG',
    category: 'June 2021',
    gallery_id: 1,
    filename: 'cali8.jpg',
    description:'Cali boys',
  },
  {
    title: 'Cali',
    artist: 'FUGG',
    category: 'June 2021',
    gallery_id: 1,
    filename: 'cali9.jpg',
    description:'Cali boys',
  },
  {
    title: 'Cali',
    artist: 'FUGG',
    category: 'June 2021',
    gallery_id: 1,
    filename: 'cali10.jpg',
    description:'Cali boys',
  },
  {
    title: 'Cali',
    artist: 'FUGG',
    category: 'June 2021',
    gallery_id: 1,
    filename: 'cali11.jpg',
    description:'Cali boys',
  },
  {
    title: 'Cali',
    artist: 'FUGG',
    category: 'June 2021',
    gallery_id: 1,
    filename: 'cali12.jpg',
    description:'Cali boys',
  },
  {
    title: 'Kylie',
    artist: 'FUGG',
    category: 'June 2020',
    gallery_id: 2,
    filename: 'k1.jpg',
    description: 'Freesoul',
  },
  {
    title: 'Kylie',
    artist: 'FUGG',
    category: 'June 2020',
    gallery_id: 2,
    filename: 'k2.jpg',
    description: 'Freesoul',
  },
  {
    title: 'Kylie',
    artist: 'FUGG',
    category: 'June 2020',
    gallery_id: 2,
    filename: 'k3.jpg',
    description: 'Freesoul',
  },
  {
    title: 'Kylie',
    artist: 'FUGG',
    category: 'June 2020',
    gallery_id: 2,
    filename: 'k4.jpg',
    description: 'Freesoul',
  },
  {
    title: 'Kylie',
    artist: 'FUGG',
    category: 'June 2020',
    gallery_id: 2,
    filename: 'k5.jpg',
    description: 'Freesoul',
  },
  {
    title: 'Kylie',
    artist: 'FUGG',
    category: 'June 2020',
    gallery_id: 2,
    filename: 'k6.jpg',
    description: 'Freesoul',
  },
  {
    title: 'Kylie',
    artist: 'FUGG',
    category: 'June 2020',
    gallery_id: 2,
    filename: 'k7.jpg',
    description: 'Freesoul',
  },
  {
    title: 'Kylie',
    artist: 'FUGG',
    category: 'June 2020',
    gallery_id: 2,
    filename: 'k8.jpg',
    description: 'Freesoul',
  },
  {
    title: 'Kylie',
    artist: 'FUGG',
    category: 'June 2020',
    gallery_id: 2,
    filename: 'k9.jpg',
    description: 'Freesoul',
  },
  {
    title: 'Kylie',
    artist: 'FUGG',
    category: 'June 2020',
    gallery_id: 2,
    filename: 'k10.jpg',
    description: 'Freesoul',
  },
  {
    title: 'Destiny',
    artist: 'FUGG',
    category: 'September 2021',
    gallery_id: 3,
    filename: 'd1.jpg',
    description: 'Charming',
  },
  {
    title: 'Destiny',
    artist: 'FUGG',
    category: 'September 2021',
    gallery_id: 3,
    filename: 'd2.jpg',
    description: 'Charming',
  },
  {
    title: 'Destiny',
    artist: 'FUGG',
    category: 'September 2021',
    gallery_id: 3,
    filename: 'd5.jpg',
    description: 'Charming',
  },
  {
    title: 'Destiny',
    artist: 'FUGG',
    category: 'September 2021',
    gallery_id: 3,
    filename: 'd8.jpg',
    description: 'Charming',
  },
  {
    title: 'Destiny',
    artist: 'FUGG',
    category: 'September 2021',
    gallery_id: 3,
    filename: 'd11.jpg',
    description: 'Charming',
  },
  {
    title: 'Destiny',
    artist: 'FUGG',
    category: 'September 2021',
    gallery_id: 3,
    filename: 'd14.jpg',
    description: 'Charming',
  },
  {
    title: 'Destiny',
    artist: 'FUGG',
    category: 'September 2021',
    gallery_id: 3,
    filename: 'd15.jpg',
    description: 'Charming',
  },
  {
    title: 'Destiny',
    artist: 'FUGG',
    category: 'September 2021',
    gallery_id: 3,
    filename: 'd18.jpg',
    description: 'Charming',
  },
  {
    title: 'Destiny',
    artist: 'FUGG',
    category: 'September 2021',
    gallery_id: 3,
    filename: 'd20.jpg',
    description: 'Charming',
  },
  {
    title: 'Destiny',
    artist: 'FUGG',
    category: 'September 2021',
    gallery_id: 3,
    filename: 'd21.jpg',
    description: 'Charming',
  },
  {
    title: 'DUO',
    artist: 'FUGG',
    category: 'July 2021',
    gallery_id: 4,
    filename: 'duo1.jpg',
    description: 'Double trouble.',
  },
  {
    title: 'DUO',
    artist: 'FUGG',
    category: 'July 2021',
    gallery_id: 4,
    filename: 'duo2.jpg',
    description: 'Double trouble.',
  },
  {
    title: 'DUO',
    artist: 'FUGG',
    category: 'July 2021',
    gallery_id: 4,
    filename: 'duo3.jpg',
    description: 'Double trouble.',
  },
  {
    title: 'DUO',
    artist: 'FUGG',
    category: 'July 2021',
    gallery_id: 4,
    filename: 'duo4.jpg',
    description: 'Double trouble.',
  },
  {
    title: 'DUO',
    artist: 'FUGG',
    category: 'July 2021',
    gallery_id: 4,
    filename: 'duo5.jpg',
    description: 'Double trouble.',
  },
  {
    title: 'DUO',
    artist: 'FUGG',
    category: 'July 2021',
    gallery_id: 4,
    filename: 'duo6.jpg',
    description: 'Double trouble.',
  },
  {
    title: 'DUO',
    artist: 'FUGG',
    category: 'July 2021',
    gallery_id: 4,
    filename: 'duo7.jpg',
    description: 'Double trouble.',
  },
  {
    title: 'DUO',
    artist: 'FUGG',
    category: 'July 2021',
    gallery_id: 4,
    filename: 'duo8.jpg',
    description: 'Double trouble.',
  },
  {
    title: 'DUO',
    artist: 'FUGG',
    category: 'July 2021',
    gallery_id: 4,
    filename: 'duo9.jpg',
    description: 'Double trouble.',
  },
  {
    title: 'DUO',
    artist: 'FUGG',
    category: 'July 2021',
    gallery_id: 4,
    filename: 'duo10.jpg',
    description: 'Double trouble.',
  },
];

const seedPhotos = () => Photo.bulkCreate(photodata);

module.exports = seedPhotos;
